"""Initial schema with all tables

Revision ID: 53192a75b151
Revises: 
Create Date: 2025-12-08 16:56:29.236629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '53192a75b151'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('reported_energy', sa.String(length=10), nullable=False),
    sa.Column('predicted_energy', sa.String(length=10), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('context_switches', sa.Integer(), nullable=True),
    sa.Column('time_since_break', sa.Integer(), nullable=True),
    sa.Column('energy_accuracy', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_energy_log_timestamp', 'energy_logs', ['timestamp'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_energy_level', sa.String(length=10), nullable=False),
    sa.Column('requires_focus', sa.Boolean(), nullable=True),
    sa.Column('context_category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurrence_rule', sa.String(length=200), nullable=True),
    sa.Column('sync_enabled', sa.Boolean(), nullable=True),
    sa.Column('apple_reminder_id', sa.String(length=200), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index('idx_task_deadline', 'tasks', ['deadline'], unique=False)
    op.create_index('idx_task_status', 'tasks', ['status'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('typical_work_start', sa.String(length=5), nullable=True),
    sa.Column('typical_work_end', sa.String(length=5), nullable=True),
    sa.Column('preferred_break_duration', sa.Integer(), nullable=True),
    sa.Column('peak_energy_times', sqlite.JSON(), nullable=True),
    sa.Column('low_energy_times', sqlite.JSON(), nullable=True),
    sa.Column('max_focus_duration', sa.Integer(), nullable=True),
    sa.Column('context_switch_penalty', sa.Integer(), nullable=True),
    sa.Column('buffer_time_between_tasks', sa.Integer(), nullable=True),
    sa.Column('planning_horizon_days', sa.Integer(), nullable=True),
    sa.Column('default_task_duration', sa.Integer(), nullable=True),
    sa.Column('default_sync_to_reminders', sa.Boolean(), nullable=True),
    sa.Column('default_sync_to_calendar', sa.Boolean(), nullable=True),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('llm_provider', sa.String(length=20), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('apple_event_id', sa.String(length=200), nullable=True),
    sa.Column('is_all_day', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('related_task_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['related_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_operations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('operation_type', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_created', 'sync_operations', ['created_at'], unique=False)
    op.create_index('idx_sync_status', 'sync_operations', ['status'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('depends_on_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE')
    )
    op.create_table('time_blocks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=10), nullable=False),
    sa.Column('is_flexible', sa.Boolean(), nullable=True),
    sa.Column('apple_calendar_event_id', sa.String(length=200), nullable=True),
    sa.Column('sync_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('energy_level_required', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_time_block_start', 'time_blocks', ['start_time'], unique=False)
    op.create_index('idx_time_block_task', 'time_blocks', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_time_block_task', table_name='time_blocks')
    op.drop_index('idx_time_block_start', table_name='time_blocks')
    op.drop_table('time_blocks')
    op.drop_table('task_dependencies')
    op.drop_index('idx_sync_status', table_name='sync_operations')
    op.drop_index('idx_sync_created', table_name='sync_operations')
    op.drop_table('sync_operations')
    op.drop_table('calendar_events')
    op.drop_table('user_preferences')
    op.drop_index('idx_task_status', table_name='tasks')
    op.drop_index('idx_task_deadline', table_name='tasks')
    op.drop_index('idx_task_created_at', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_energy_log_timestamp', table_name='energy_logs')
    op.drop_table('energy_logs')
    # ### end Alembic commands ###
